version: "2.0" 
services: 
  location-api: 
    build: .
    ports:
      - "8080:8080"
    environment:
    - DB_URL=mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
